orderBoardApp/config/routes.rb
Rails.application.routes.draw do
  resources :logins do
    resources :mainorderboards
  end 
  resources :mainorderboards do
    resources :suborders
  end
  resources :suborders do
    resources :products
  end

 resource :session, only: [:new, :create, :destroy]

  
  
  
  

  

  
  root 'sessions#new'

  

  

  

end

orderBoardApp/app/models/customer.rb
class Customer
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :email, type: String
  field :phone, type: String
  has_many :orders
end

orderBoardApp/app/models/login.rb
require 'bcrypt'

class Login
  include Mongoid::Document
  include ActiveModel::SecurePassword
  field :firstName, type: String
  field :lastName, type: String
  field :username, type: String
  field :password_digest, type: String

  has_secure_password

  has_many :mainorderboards
end

orderBoardApp/app/models/mainorderboard.rb
class Mainorderboard
  include Mongoid::Document
  field :name, type: String
  
  has_many :suborders
  belongs_to :login
end

orderBoardApp/app/models/product.rb
class Product
  include Mongoid::Document
  field :name, type: String
  field :price, type: String
  field :description, type: String
  field :picture, type: String
  field :unit, type: String
  belongs_to :suborder
  belongs_to :productlist
  
end

orderBoardApp/app/models/suborder.rb
class Suborder
  include Mongoid::Document
  field :vendorname, type: String
  field :email, type: String
  
  belongs_to :mainorderboard
  has_many :products
	 
end

orderBoardApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :current_mainorderboard
  def current_user
  	@current_user ||= Login.find(session[:login_id]) if session[:login_id]
  end
  # def current_mainorderboard
  # 	@current_mainorderboard ||= Mainorderboard.find(session[:login_id]) if session[:login_id]
  # end
end

orderBoardApp/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
		
		def index
			@customers = Customer.all
		end

		def new
			@customer = Customer.new
			@customer = Customer.where(:customer_id => @customer.id)
			@customer = current_user.customer

		end

		def create
			@customer = Customer.find(params[:customer_id])
			@customer = Customer.new(params.require(:customer_id).permit(:name, :email))
			puts '*********' + @customer.inspect
			if @customer.save
				redirect_to customer_path
			else
				render 'new'
			end
		end

		# def destroy
		# 	Decision.find(params[:id]).destroy
		# 	redirect_to :customer_path
		# end

end

orderBoardApp/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def index
		@login = Login.all
	end

	def show
		@login = Login.find(params[:id])
	end

	def new
		@login = Login.new
	end

	def create
		@login = Login.new(params.require(:login).permit(:firstName, :lastName, :username, :password, :password_confirmation))
		if @login.save
			redirect_to new_session_path
		else
			render 'new'
		end
	end

	def edit 
		@login = Login.find(params[:id])
	end

	def update
		@login = Login.find(params[:id])
		if @login.update_attributes(params.require(:login).permit(:firstName, :lastName, :email))
			redirect_to logins_path
		else
			render 'edit'
		end
	end

	def destroy
		@login = Login.find(params[:id])
		@logins.destroy
		redirect_to logins_path
	end

end

orderBoardApp/app/controllers/mainorderboards_controller.rb
 class MainorderboardsController < ApplicationController
	def index
			
		@mainorderboards = current_user.mainorderboards
	end

	def show
		
		@login = Login.find(params[:login_id])
		@mainorderboards = current_user.mainorderboards
	end

	
	def new
		@login = Login.find(params[:login_id])
		@mainorderboard = Mainorderboard.new
		
	end

	def create
		
		@mainorderboards = current_user.mainorderboards.new(
			params.require(:mainorderboard).permit(:name)
			)
		if @mainorderboards.save
			redirect_to login_mainorderboards_path(@current_user.id)

		else
			render 'new'
		end
	end
	





	def destroy
		@mainorderboard = Mainorderboard.find(params[:id])
		@mainorderboard.destroy
		redirect_to mainorderboards_path
	end
end

	# def edit 
	# 	@login = Login.find(params[:id])
	# end

	# def update
	# 	@login = Login.find(params[:id])
	# 	if @login.update_attributes(params.require(:login).permit(:firstName, :lastName, :email))
	# 		redirect_to logins_path
	# 	else
	# 		render 'edit'
	# 	end
	# end

	# def destroy
	# 	@login = Login.find(params[:id])
	# 	@logins.destroy
	# 	redirect_to logins_path
	# end

orderBoardApp/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		
		@suborder = Suborder.where(id: params[:suborder_id]).first	
		@products = @suborder.products
		
		
	end

	def show
		@suborder = Suborder.where(id: params[:suborder_id]).first
		@product = Product.find(params[:id])
	end

	def new
		@mainorderboard = Mainorderboard.where(id: params[:mainorderboard_id]).first
		@suborder = Suborder.where(id: params[:suborder_id]).first
		@product = Product.new
	end

	def create
		@suborder = Suborder.where(id: params[:suborder_id]).first
		@product = @suborder.products.new(params.require(:product).permit(:name, :price, :description, :picture, :unit))
		if @product.save
      redirect_to suborder_products_path(@suborder.id)
      else
      render 'new'
    end
	end
end

orderBoardApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@login = Login.new
		@is_login = true
	end

	def create
		#find the user that is trying to login

		u = Login.where(username: params[:login][:username]).first
		# if they type the password correctly
		if u && u.authenticate(params[:login][:password])
			
			#if the condition is met
			#store as a cookie in the users browser the id of them
			#indicating that they are logged in
			session[:login_id] = u.id.to_s
			@current_login = u
			@mainorderboard = Mainorderboard.where(:login_id => @current_login.id).first

			if @maidorderboard != nil
				redirect_to login_mainorderboard_path(@current_login.id, @mainorderboard.id)
			else
				redirect_to login_path(@current_login.id)
			end
		else

			# go back to the login page
			redirect_to new_session_path
		end
	end

	def destroy
		reset_session
		redirect_to logins_path
	end
end

orderBoardApp/app/controllers/suborders_controller.rb
class SubordersController < ApplicationController
 
  def index
    
    @mainorderboard = Mainorderboard.where(id: params[:mainorderboard_id]).first
    @suborders = @mainorderboard.suborders
  end

  def show
    
   
    @mainorderboard = Mainorderboard.find(params[:mainorderboard_id])
    @suborder = Suborder.find(params[:id])
    

    
    
  end
  
  def new
    # @current_user = current_user.mainorderboards
    @mainorderboard = Mainorderboard.where(id: params[:mainorderboard_id]).first
    @suborder = Suborder.new
  end

  def create
    @mainorderboard = Mainorderboard.where(id: params[:mainorderboard_id]).first
    @suborder = @mainorderboard.suborders.new(
      params.require(:suborder).permit(:vendorname, :email)
      )
    if @suborder.save
      redirect_to mainorderboard_suborders_path(@mainorderboard.id)



    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

orderBoardApp/app/helpers/application_helper.rb
module ApplicationHelper
end

orderBoardApp/app/helpers/customers_helper.rb
module CustomersHelper
end

orderBoardApp/app/helpers/logins_helper.rb
module LoginsHelper
end

orderBoardApp/app/helpers/mainorderboards_helper.rb
module MainorderboardsHelper
end

orderBoardApp/app/helpers/products_helper.rb
module ProductsHelper
end

orderBoardApp/app/helpers/suborders_helper.rb
module SubordersHelper
end

orderBoardApp/app/views/customers/index.html.erb
<% @customers.each do |l| %>
	<p><%= l.name %>
	<%= l.address %>
	<%= l.email %>
	<%= l.phone %>
	<%= link_to 'Create Order', customer_mainorderboards_path(l.id) %>
	
</p>
	<% end %>

	<h1><%= link_to 'New', customers_new_path %></h1>

orderBoardApp/app/views/customers/new.html.erb
<%= form_for @customer do |l| %>
	Name: <%= l.text_field :name %>
	Address: <%= l.text_field :address %>
	Email: <%= l.text_field :email %>
	Phone: <%= l.text_field :phone %>
	Add: <%= l.submit "Add" %>
	<% end %>

	<%= link_to "Back to the List", customers_path %>

orderBoardApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>orderboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <!-- font link -->
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>

  
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"> orderboard loves you</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Guide <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Delivery <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Past Orders <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account Info <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#"><% if current_user %><%= link_to "Log out", session_path, method: :delete %></a></li>
              <li><a href="#"><% else %><%= link_to "Sign up", new_login_path %></a></li>
              <li><a href="#"><%= link_to "Log in", new_session_path %><% end %></a></li>

            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


<%= yield %>

</body>

</html>

orderBoardApp/app/views/logins/index.html.erb
 <h1>Login Page</h1>
<% @login.each do |l| %>
	<p><%= l.firstName %>
	<%= l.lastName %>
	<%= l.username %>
	<%= l.password_digest %>
</p>

	<% end %>
<%= link_to 'Show', logins_path %>
<%= link_to 'New', new_login_path %>

orderBoardApp/app/views/logins/new.html.erb
	<div class="container-fluid body_wrapper">
      <div class="row">
        <div class="col-xs-12">
          <h1 class="signupheader">make your day suck less</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4">
        </div>
        <div class="col-xs-2">
         
          <%= l.text_field :firstName, class: "form-control button", placeholder: "first name"%>
        </div>
        <div class="col-xs-2">
          <%= l.text_field :lastName, class: "form-control button", placeholder: "last name" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
          <%= l.text_field :username, class: "button form-control", placeholder: "pick your username" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
        	<%= l.password_field :password, class: "button form-control", placeholder:"pick a unique password" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
        	<%= l.password_field :password_confirmation, class: "button form-control", placeholder: "confirm your new password" %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-4 col-xs-offset-4 button">
        	<%= l.submit "button that works and I hate it" %>
          <button type="button" class="btn button btn-default">submit here</button>
        </div>
      </div>
    </div>
    <% end %>

orderBoardApp/app/views/logins/show.html.erb
<h1>Welcome to your orderboard account</h1>

<h2><%= link_to 'Create a new orderboard', new_login_mainorderboard_path(@login.id) %></h2>

<h2><%= link_to 'Work on a existing orderboard', login_mainorderboards_path(@login.id) %></h2>

orderBoardApp/app/views/mainorderboards/index.html.erb
<h1>These are your past orders (Days)</h1>
        	
        	<ul>
        	<% @mainorderboards.each do |m| %>
          
          <li><b><%= m.name %>
          	<%= link_to ' do work on this', mainorderboard_suborders_path(m.id)%></li>
          <% end %>
        </ul>
        <h2><%= link_to 'Create a new orderboard', new_login_mainorderboard_path(@login.id) %></h2>
          

orderBoardApp/app/views/mainorderboards/new.html.erb
<h1>What day is this orderboard for</h1>
<%= form_for [@current_user, @mainorderboard] do |l| %>
	<%= l.text_field :name %>
  
	Add: <%= l.submit "Add" %>
	<% end %>

orderBoardApp/app/views/mainorderboards/show.html.erb
<h1>Welcome to</h1>



<%= @mainorderboard.name %><h1>s orderboard</h1>
<%= @login.id %>

<h2><%= link_to 'go to previous orders', login_mainorderboards_path(@login.id) %></h2>




<h2><%= link_to 'Add a Vendor Orderboard',  new_mainorderboard_suborder_path(@mainorderboard.id) %></h2>

orderBoardApp/app/views/products/index.html.erb
<h1>This is a list of products on your order guide</h1>

<ul>
  <% @products.each do |p| %>
    <li><b><%= p.name %> </li>
    <% end %>
</ul>

<h2><%= link_to 'Add a Product to the Orderboard',   new_suborder_product_path(@suborder.id) %></h2>

         

orderBoardApp/app/views/products/new.html.erb
<h1> Welp you got to the add a product page</h1>

<h1>Time to add one</h1>

<%= form_for [@suborder, @product] do |l| %>
	Product: <%= l.text_field :name %>
  
	
	Create a new product: <%= l.submit "Add" %>
	<% end %>

	<h2><%= link_to 'Go Back',   suborder_products_path(@suborder.id) %></h2>

orderBoardApp/app/views/suborders/create.html.erb
<h1>Suborders#create</h1>
<p>Find me in app/views/suborders/create.html.erb</p>

orderBoardApp/app/views/suborders/destroy.html.erb
<h1>Suborders#destroy</h1>
<p>Find me in app/views/suborders/destroy.html.erb</p>

orderBoardApp/app/views/suborders/edit.html.erb
<h1>Suborders#edit</h1>
<p>Find me in app/views/suborders/edit.html.erb</p>

orderBoardApp/app/views/suborders/index.html.erb
<h1>This is where the vendor index for this day will be</h1>


<ul>
        	<% @suborders.each do |s| %>
          
          <li><b><%= s.vendorname %> <%= link_to 'view orderboard', mainorderboard_suborder_path(@mainorderboard.id, s.id)%></li>
          	
        
          <% end %>
        </ul>
        
          	<%= link_to 'Add a Vendor', new_mainorderboard_suborder_path(@mainorderboard.id) %>
          	

orderBoardApp/app/views/suborders/new.html.erb
<h1>This is where you will add a vendor</h1>

<%= form_for [@mainorderboard, @suborder] do |l| %>
	Vendor Name: <%= l.text_field :vendorname %>
  
	
	Create a new Vendor: <%= l.submit "Add" %>
	<% end %>

orderBoardApp/app/views/suborders/show.html.erb
<h1>List the Vendors Here</h1>
	<%= @suborder.vendorname %>
	<h2><%= link_to 'Back to main orderboard', mainorderboard_suborders_path(@mainorderboard.id) %> </h2>
	<h2><%= link_to 'Add a Product to the Orderboard',   new_suborder_product_path(@suborder.id) %></h2>
	


        
	

orderBoardApp/app/views/suborders/update.html.erb
<h1>Suborders#update</h1>
<p>Find me in app/views/suborders/update.html.erb</p>